// Copyright (c) Microsoft Corporation. All rights reserved.

namespace Microsoft.Greenlight.Shared.Enums;

/// <summary>
/// Defines the types of outputs that can be generated by Flow Tasks.
/// </summary>
public enum FlowTaskOutputType
{
    /// <summary>
    /// Unknown or unspecified output type.
    /// </summary>
    Unknown = 0,

    /// <summary>
    /// Generates a text summary of the collected information.
    /// </summary>
    TextSummary = 1,

    /// <summary>
    /// Invokes an MCP (Model Context Protocol) tool with collected field values.
    /// </summary>
    McpToolInvocation = 2,

    /// <summary>
    /// Generates a document using a document process template.
    /// </summary>
    Document = 3,

    /// <summary>
    /// Sends an email with the collected information.
    /// </summary>
    Email = 4,

    /// <summary>
    /// Creates or updates a database record.
    /// </summary>
    DatabaseRecord = 5,

    /// <summary>
    /// Generates a file (PDF, DOCX, etc.) from collected data.
    /// </summary>
    FileGeneration = 6,

    /// <summary>
    /// Returns a hyperlink/URL to an external resource (e.g., generated document, web page).
    /// </summary>
    Link = 7
}
