// Copyright (c) Microsoft Corporation. All rights reserved.

using System;
using System.Collections.Generic;

namespace Microsoft.Greenlight.Shared.Contracts.FlowTasks;

/// <summary>
/// Represents the result of a Flow Task execution operation.
/// </summary>
public class FlowTaskExecutionResult
{
    /// <summary>
    /// Gets or sets the execution ID.
    /// </summary>
    public Guid ExecutionId { get; set; }

    /// <summary>
    /// Gets or sets the current state of the execution.
    /// </summary>
    public FlowTaskExecutionState State { get; set; } = FlowTaskExecutionState.NotStarted;

    /// <summary>
    /// Gets or sets the response message to show to the user.
    /// </summary>
    public string ResponseMessage { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets whether the execution is complete.
    /// </summary>
    public bool IsComplete { get; set; }

    /// <summary>
    /// Gets or sets whether the execution was successful.
    /// </summary>
    public bool IsSuccess { get; set; }

    /// <summary>
    /// Gets or sets any error message if the execution failed.
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Gets or sets the current section being processed.
    /// </summary>
    public string? CurrentSection { get; set; }

    /// <summary>
    /// Gets or sets the current requirement being collected.
    /// </summary>
    public string? CurrentRequirement { get; set; }

    /// <summary>
    /// Gets or sets the progress percentage (0-100).
    /// </summary>
    public int ProgressPercentage { get; set; }

    /// <summary>
    /// Gets or sets the collected requirement values.
    /// </summary>
    public Dictionary<string, object?> CollectedValues { get; set; } = new Dictionary<string, object?>();

    /// <summary>
    /// Gets or sets any suggested actions for the user.
    /// </summary>
    public List<string> SuggestedActions { get; set; } = new List<string>();

    /// <summary>
    /// Gets or sets any generated outputs if execution is complete.
    /// </summary>
    public List<FlowTaskOutput>? Outputs { get; set; }
}

/// <summary>
/// Represents the state of a Flow Task execution.
/// </summary>
public enum FlowTaskExecutionState
{
    /// <summary>
    /// The Flow Task has not been started.
    /// </summary>
    NotStarted,

    /// <summary>
    /// The Flow Task is currently collecting requirements.
    /// </summary>
    CollectingRequirements,

    /// <summary>
    /// The Flow Task is validating collected requirements.
    /// </summary>
    ValidatingRequirements,

    /// <summary>
    /// The Flow Task is awaiting user confirmation to proceed with execution.
    /// </summary>
    AwaitingConfirmation,

    /// <summary>
    /// The Flow Task is executing outputs.
    /// </summary>
    ExecutingOutputs,

    /// <summary>
    /// The Flow Task has completed successfully.
    /// </summary>
    Completed,

    /// <summary>
    /// The Flow Task was cancelled by the user.
    /// </summary>
    Cancelled,

    /// <summary>
    /// The Flow Task encountered an error.
    /// </summary>
    Failed
}

/// <summary>
/// Represents an output generated by a Flow Task.
/// </summary>
public class FlowTaskOutput
{
    /// <summary>
    /// Gets or sets the output name.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the output type.
    /// </summary>
    public string Type { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the output content.
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the content type.
    /// </summary>
    public string ContentType { get; set; } = "text/plain";

    /// <summary>
    /// Gets or sets any metadata associated with the output.
    /// </summary>
    public Dictionary<string, object?>? Metadata { get; set; }
}