# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- features/*

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Aspire Install'
  inputs:
    command: custom
    custom: 'workload '
    arguments: 'install aspire --source https://api.nuget.org/v3/index.json'

- task: NuGetAuthenticate@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '34c82829-ae45-4ed4-8b6c-f6bfa0427c71/1cb4a1b4-2407-4486-b5e7-e59d597daf32'
    includeNuGetOrg: false

- task: DotNetCoreCLI@2
  displayName: 'DotNet Solution Build'
  inputs:
    command: 'build'
    arguments: '--no-restore'
    projects: 'src/ProjectVico.V2.sln'
    workingDirectory: 'src/'
