# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- features/*

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Aspire Install'
  inputs:
    command: custom
    custom: 'workload '
    arguments: 'install aspire --source https://api.nuget.org/v3/index.json'

- task: NuGetCommand@2
  displayName: 'Azure Artifacts NuGet Restore'
  inputs:
    command: 'restore'
    restoreSolution: 'src/ProjectVico.v2.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'src/NuGet.config'

- task: DotNetCoreCLI@2
  displayName: 'DotNet Solution Build'
  inputs:
    command: 'build'
    arguments: '--no-restore'
    projects: 'src/ProjectVico.V2.sln'
    workingDirectory: 'src/'
