// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.Greenlight.Shared.Data.Sql;

#nullable disable

namespace Microsoft.Greenlight.Shared.Migrations
{
    [DbContext(typeof(DocGenerationDbContext))]
    [Migration("20240518182824_RenameDynamicDocumentProcessDefinitionTable")]
    partial class RenameDynamicDocumentProcessDefinitionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.BoundingPolygon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoundingRegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("X")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal>("Y")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.HasKey("Id");

                    b.HasIndex("BoundingRegionId");

                    b.HasIndex("IsActive");

                    b.HasIndex("DeletedAt", "IsActive");

                    b.HasIndex("X", "Y");

                    b.ToTable("BoundingPolygons");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.BoundingRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContentNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Page")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("TableId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContentNodeId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Page");

                    b.HasIndex("TableId");

                    b.HasIndex("DeletedAt", "IsActive");

                    b.ToTable("BoundingRegions");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.ChatConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentProcessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("DeletedAt", "IsActive");

                    b.ToTable("ChatConversations", (string)null);
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthorUserInformationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReplyToChatMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<Guid?>("SummarizedByConversationSummaryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserInformationId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("ReplyToChatMessageId");

                    b.HasIndex("SummarizedByConversationSummaryId");

                    b.HasIndex("DeletedAt", "IsActive");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.ContentNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("GeneratedDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("GenerationState")
                        .HasColumnType("int");

                    b.Property<Guid?>("IngestedDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedDocumentId");

                    b.HasIndex("IngestedDocumentId");

                    b.HasIndex("IsActive");

                    b.HasIndex("ParentId");

                    b.HasIndex("DeletedAt", "IsActive");

                    b.ToTable("ContentNodes");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.ConversationSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SummaryText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("DeletedAt", "IsActive");

                    b.ToTable("ConversationSummaries");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.DocumentMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("GeneratedDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedDocumentId")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("DeletedAt", "IsActive");

                    b.ToTable("DocumentMetadata");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.DynamicDocumentProcessDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobStorageAutoImportFolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlobStorageContainerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassificationModelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ClassifyDocuments")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LogicType")
                        .HasColumnType("int");

                    b.Property<string>("Repositories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("LogicType");

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.HasIndex("DeletedAt", "IsActive");

                    b.ToTable("DynamicDocumentProcessDefinitions", (string)null);
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.GeneratedDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentProcess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("MetadataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestingAuthorOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("DeletedAt", "IsActive");

                    b.ToTable("GeneratedDocuments");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.IngestedDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassificationShortCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClassificationType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentProcess")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileHash")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IngestedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IngestionState")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("OriginalDocumentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plugin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UploadedByUserOid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentProcess");

                    b.HasIndex("FileHash");

                    b.HasIndex("IsActive");

                    b.HasIndex("DeletedAt", "IsActive");

                    b.ToTable("IngestedDocuments");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ColumnCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("IngestedDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("IngestedDocumentId");

                    b.HasIndex("IsActive");

                    b.HasIndex("DeletedAt", "IsActive");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.TableCell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("int");

                    b.Property<int?>("ColumnSpan")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("RowIndex")
                        .HasColumnType("int");

                    b.Property<int?>("RowSpan")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("TableId");

                    b.HasIndex("DeletedAt", "IsActive");

                    b.ToTable("TableCells");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.UserInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("ProviderSubjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProviderSubjectId")
                        .IsUnique();

                    b.HasIndex("DeletedAt", "IsActive");

                    b.ToTable("UserInformations");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.SagaState.DocumentGenerationSagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorOid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentProcessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MetadataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfContentNodesGenerated")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfContentNodesToGenerate")
                        .HasColumnType("int");

                    b.HasKey("CorrelationId");

                    b.ToTable("DocumentGenerationSagaStates");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.SagaState.DocumentIngestionSagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassificationShortCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentProcessName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileHash")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalDocumentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plugin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadedByUserOid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CorrelationId");

                    b.HasIndex("DocumentProcessName");

                    b.HasIndex("FileHash");

                    b.ToTable("DocumentIngestionSagaStates");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DocumentIngestionSagaState");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.SagaState.KernelMemoryDocumentIngestionSagaState", b =>
                {
                    b.HasBaseType("Microsoft.Greenlight.Shared.SagaState.DocumentIngestionSagaState");

                    b.HasDiscriminator().HasValue("KernelMemoryDocumentIngestionSagaState");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.BoundingPolygon", b =>
                {
                    b.HasOne("Microsoft.Greenlight.Shared.Models.BoundingRegion", "BoundingRegion")
                        .WithMany("BoundingPolygons")
                        .HasForeignKey("BoundingRegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoundingRegion");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.BoundingRegion", b =>
                {
                    b.HasOne("Microsoft.Greenlight.Shared.Models.ContentNode", "ContentNode")
                        .WithMany("BoundingRegions")
                        .HasForeignKey("ContentNodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.Greenlight.Shared.Models.Table", "Table")
                        .WithMany("BoundingRegions")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContentNode");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.ChatMessage", b =>
                {
                    b.HasOne("Microsoft.Greenlight.Shared.Models.UserInformation", "AuthorUserInformation")
                        .WithMany()
                        .HasForeignKey("AuthorUserInformationId");

                    b.HasOne("Microsoft.Greenlight.Shared.Models.ChatConversation", "Conversation")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.Greenlight.Shared.Models.ChatMessage", "ReplyToChatMessage")
                        .WithOne()
                        .HasForeignKey("Microsoft.Greenlight.Shared.Models.ChatMessage", "ReplyToChatMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.Greenlight.Shared.Models.ConversationSummary", "SummarizedByConversationSummary")
                        .WithMany("SummarizedChatMessages")
                        .HasForeignKey("SummarizedByConversationSummaryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AuthorUserInformation");

                    b.Navigation("Conversation");

                    b.Navigation("ReplyToChatMessage");

                    b.Navigation("SummarizedByConversationSummary");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.ContentNode", b =>
                {
                    b.HasOne("Microsoft.Greenlight.Shared.Models.GeneratedDocument", "GeneratedDocument")
                        .WithMany("ContentNodes")
                        .HasForeignKey("GeneratedDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.Greenlight.Shared.Models.IngestedDocument", "IngestedDocument")
                        .WithMany("ContentNodes")
                        .HasForeignKey("IngestedDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.Greenlight.Shared.Models.ContentNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GeneratedDocument");

                    b.Navigation("IngestedDocument");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.DocumentMetadata", b =>
                {
                    b.HasOne("Microsoft.Greenlight.Shared.Models.GeneratedDocument", "GeneratedDocument")
                        .WithOne("Metadata")
                        .HasForeignKey("Microsoft.Greenlight.Shared.Models.DocumentMetadata", "GeneratedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GeneratedDocument");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.Table", b =>
                {
                    b.HasOne("Microsoft.Greenlight.Shared.Models.IngestedDocument", "IngestedDocument")
                        .WithMany("Tables")
                        .HasForeignKey("IngestedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IngestedDocument");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.TableCell", b =>
                {
                    b.HasOne("Microsoft.Greenlight.Shared.Models.Table", "Table")
                        .WithMany("Cells")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.BoundingRegion", b =>
                {
                    b.Navigation("BoundingPolygons");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.ChatConversation", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.ContentNode", b =>
                {
                    b.Navigation("BoundingRegions");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.ConversationSummary", b =>
                {
                    b.Navigation("SummarizedChatMessages");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.GeneratedDocument", b =>
                {
                    b.Navigation("ContentNodes");

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.IngestedDocument", b =>
                {
                    b.Navigation("ContentNodes");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("Microsoft.Greenlight.Shared.Models.Table", b =>
                {
                    b.Navigation("BoundingRegions");

                    b.Navigation("Cells");
                });
#pragma warning restore 612, 618
        }
    }
}
