// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.Greenlight.Shared.Data.Sql;

#nullable disable

namespace Microsoft.Greenlight.Shared.Migrations
{
    [DbContext(typeof(DocGenerationDbContext))]
    [Migration("20250502000000_UpdateMcpPluginVersionArguments")]
    partial class UpdateMcpPluginVersionArguments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");
#pragma warning restore 612, 618
        }
    }
}